const styles = {
    form: {
        borderRadius: '5px',
        boxShadow: '0 0 40px 0 rgba(168, 129, 175, 0.3)',
        display: 'flex',
        color: '#333',
        flexWrap: 'wrap',
        fontFamily: 'sans-serif',
        gap: '1em',
        margin: '0 auto',
        maxWidth: '350px',
        padding: '3em',
        position: 'absolute',
        left: '50%',
        top: '50%',
        transform: 'translate(-50%, -50%)',
    },
    title: { fontSize: '2rem', marginTop: 0 },
    field: {
        div: { display: 'flex', flexDirection: 'column', gap: '.3em', width: '100%' },
        input: {
            padding: '.5em',
            borderRadius: '5px',
            border: 'none',
            outline: '1px solid rgba(168, 129, 175, 0.5)',
        },
        small: { color: 'tomato' },
    },
    buttonField: { border: 'none', width: '100%', textAlign: 'center' },
    submitButton: {
        backgroundColor: 'rgb(168, 129, 175)',
        border: 'none',
        borderRadius: '5px',
        color: '#fff',
        cursor: 'pointer',
        fontWeight: '700',
        marginTop: '2em',
        padding: '.8em',
        width: '100%',
    },
    modal: {
        aside: {
            backgroundColor: '#fff',
            boxShadow: '0 0 40px 0 rgba(168, 129, 175, 0.3)',
            display: 'flex',
            flexDirection: 'column',
            padding: '2em 4em',
            position: 'absolute',
            left: '50%',
            top: '50%',
            transform: 'translate(-50%, -50%)',
        },
        h1: { color: '#333' },
        p: { color: '#333' },
        button: {
            backgroundColor: 'rgb(168, 129, 175)',
            border: 'none',
            borderRadius: '5px',
            color: '#fff',
            cursor: 'pointer',
            fontWeight: '700',
            marginTop: '2em',
            padding: '.8em',
            width: 'auto',
        },
    },
};

export default styles;
